### ISSUE TITLE
Beta 3- incoming messages not received on Wifi

### ISSUE THREAD

**Issue by mgn2018** [obsidianproject/MessengerAndroid#32] opened 2018-01-03 21:35 UTC
When I switched to my 5g data connection (turned off wifi) then the replies which my contacts had sent previously suddenly all came thru. Before the messages had not shown (when on Wifi). Samsung galaxy s8

**Comment by netsfx** [comment] 2018-01-04 00:11
@mgn2018 perhaps that reset the whole connection.

Can you test, if it works in such a condition also by switching on/off wifi, or by killing and restarting the app? My theory is it's not an inability to send via wifi in principle, but rather the connection got 'stuck'.

**Comment by netsfx** [comment] 2018-01-17 21:00
closing this, because it cannot be reproduced.

**Closed by netsfx** 2018-01-17 21:00 UTC
